### ISSUE TITLE
Interest check for additional features

### ISSUE THREAD

**Issue by jspngh** [japaric/mfrc522#12]
This repository hasn't been active for a while now, so I wanted to create this issue before opening a PR.
A couple of years ago, I made a port of the [Arduino MFRC522 driver](https://github.com/miguelbalboa/rfid).
Recently, I've converted this to `no_std` and used this crate as a basis.
My hope is to get the changes merged into this repository and deprecate the other crate.
Please [have a look](https://gitlab.com/jspngh/rfid-rs) and let me know what you think.

**Comment by jspngh** [comment]
Thanks for the response @japaric! If you could add me to the `mfrc522` crate that would be great. My crates.io username is the same as on GitHub, so `jspngh`. Whether to keep this repository or deprecate it, is up to you, either is fine for me.

@fridtjof, thanks for the heads up, I'll check it out.

**Comment by japaric** [comment]
thanks, @jspngh. I have sent you an owner invite on crates.io
